require 'core/options'
require 'core/keymaps'
require 'core/colors'

require 'packer_init'

require 'plugins/cmp'
require 'plugins/lsp'
require 'plugins/nvim-tree-cfg'
require 'plugins/telescope'
require 'plugins/treesitter'
require 'plugins/bufferline'
require 'plugins/lualine'
require 'plugins/indent-line'
require 'plugins/gitsigns'
require 'plugins/comment'
require 'plugins/autopairs'
require 'plugins/copilot'
