pulse.cmd = [
  { cmd = "load-module" args = "module-null-sink sink_name=game_audio sink_properties=device.description=GameAudio" }
  { cmd = "load-module" args = "module-null-sink sink_name=discord_audio sink_properties=device.description=DiscordAudio" }
  { cmd = "load-module" args = "module-null-sink sink_name=music_audio sink_properties=device.description=MusicAudio" }
]
